version: '3'
services:
  web_01:
    build: './apache'
    image: httpd:latest
    depends_on:
    - fpm
    volumes:
    - web_data:/usr/local/apache2/htdocs
    - web_conf:/usr/local/apache2/conf
    - web_logs:/var/log/apache2
  web_02:
    build: './apache'
    image: httpd:latest
    depends_on:
      - fpm
    volumes:
      - web_data:/usr/local/apache2/htdocs
      - web_conf:/usr/local/apache2/conf
      - web_logs:/var/log/apache2
  fpm:
    build: './fpm'
    image: php:7.1-fpm
    volumes:
      - web_data:/usr/local/apache2/htdocs
  haproxy:
    build: './haproxy'
    image: haproxy:latest
    depends_on:
      - web_01
      - web_02
      - redis
    ports:
      - "8989:80"
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
  redis:
    image: "redis:latest"
  logstash:
    build: './logstash'
    image: "docker.elastic.co/logstash/logstash:6.2.4"
    depends_on:
      - elasticsearch
      - web_01
      - web_02
    volumes:
      - web_logs:/var/log/apache2
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.4"
    environment:
      - cluster.name=elastic-docker
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.4"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  jenkins:
    image: "jenkins/jenkins:lts"
    build: './jenkins'
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
   web_data:
   web_conf:
   web_logs:
   haproxy_conf:
   elasticdata:
   jenkins_home:
